[prune]
  go-tests = true
  unused-packages = true

#[[constraint]]
#  name = "github.com/xenolf/lego"
#  version = "1.0.1"

# CLI interface
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

# Configuration storage
[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"
[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.16.0"
