[prune]
  go-tests = true
  unused-packages = true

# CLI interface
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

# Configuration storage
[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"
[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "1d3f30b51784bec5aad268e59fd3c2fc1c2fe73f"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.16.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/xenolf/lego"
  revision = "2add6910e6f2fbcf8542cb6ebde771f3260424fc"
